### ISSUE TITLE
can you send me scc.war file?

### ISSUE THREAD

**Issue by yingshang** [therealchunt/ssc#1]
can you send me scc.war file?
thanks

**Comment by therealchunt** [comment]
The software needs to be procured from Micro Focus Security Fortify.

**Comment by yingshang** [comment]
i have fortify sca software,but i haven't scc.war

**Comment by therealchunt** [comment]
You should reach out to your Fortify account team. If you don't know who they are for your company, you may go here and "Contact Sales" https://software.microfocus.com/en-us/products/static-code-analysis-sast/overview

**Comment by yingshang** [comment]
The software I used is leaked by others, but others don't have SSC.WAR
